# Docker Compose
# https://docs.docker.com/compose/
#
# Usage: test up

version: "3"
services:
  app:
    image: docker-hugo-app-test:0.1.1
    environment: &environment
      - STAGE=testing
    build:
      args:
        stage: test
